/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */

public class Depreciar extends javax.swing.JFrame {

    /**
     * Creates new form ListaClitenesNaturales
     */
    DefaultTableModel modelo;
    
    public Depreciar() {
        initComponents();
        setLocationRelativeTo(null); 
        modelo();
    }
    
    private void modelo() {
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Año-mes-dia");
        modelo.addColumn("Cuota a depreciar");
        modelo.addColumn("Depreciacion acumulada");
        modelo.addColumn("Valor en llibro");
        
        Tablacliente.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablacliente = new javax.swing.JTable();
        BtnVer = new javax.swing.JButton();
        BtnVer1 = new javax.swing.JButton();
        BtnVer2 = new javax.swing.JButton();
        BtnVer3 = new javax.swing.JButton();
        BtnVer4 = new javax.swing.JButton();
        BtnVer5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 660));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEPRECIACION DE ACTIVO FIJO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 20, 400, 70);

        Tablacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tablacliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 200, 790, 380);

        BtnVer.setBackground(new java.awt.Color(0, 153, 0));
        BtnVer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnVer.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer.setText("MES");
        BtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVer);
        BtnVer.setBounds(360, 130, 90, 30);

        BtnVer1.setBackground(new java.awt.Color(0, 153, 0));
        BtnVer1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnVer1.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer1.setText("CALCULAR");
        BtnVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVer1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVer1);
        BtnVer1.setBounds(140, 130, 90, 30);

        BtnVer2.setBackground(new java.awt.Color(0, 153, 0));
        BtnVer2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnVer2.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer2.setText("DIA");
        BtnVer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVer2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVer2);
        BtnVer2.setBounds(470, 130, 90, 30);

        BtnVer3.setBackground(new java.awt.Color(0, 153, 0));
        BtnVer3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnVer3.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer3.setText("AÑO");
        BtnVer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVer3ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVer3);
        BtnVer3.setBounds(250, 130, 90, 30);

        BtnVer4.setBackground(new java.awt.Color(0, 153, 0));
        BtnVer4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnVer4.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer4.setText("VER");
        BtnVer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVer4ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVer4);
        BtnVer4.setBounds(250, 130, 90, 30);

        BtnVer5.setBackground(new java.awt.Color(0, 153, 0));
        BtnVer5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnVer5.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer5.setText("VER");
        BtnVer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVer5ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVer5);
        BtnVer5.setBounds(250, 130, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        jLabel1.setText("SAFJKSDKFJSDFNJNKSFJNKDFJNKJNK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 970, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed
        // TODO add your handling code here:
        DetalleDepreciar vista = new DetalleDepreciar();
        vista.setVisible(true);
    }//GEN-LAST:event_BtnVerActionPerformed

    private void BtnVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVer1ActionPerformed

    private void BtnVer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVer2ActionPerformed

    private void BtnVer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVer3ActionPerformed

    private void BtnVer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVer4ActionPerformed

    private void BtnVer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVer5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVer;
    private javax.swing.JButton BtnVer1;
    private javax.swing.JButton BtnVer2;
    private javax.swing.JButton BtnVer3;
    private javax.swing.JButton BtnVer4;
    private javax.swing.JButton BtnVer5;
    private javax.swing.JTable Tablacliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
