/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorActivo;
import Controlador.ControladorCategoria;
import Controlador.ControladorSubCategoria;
import Controlador.ControladorVenta;
import Modelo.Activo;
import Modelo.Movimiento;
import Modelo.SubCategoria;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PEREZ
 */
public class ListaVentasRealizadas extends javax.swing.JFrame {

    /**
     * Creates new form ListaCatalago
     */
    DefaultTableModel modelo;
    ControladorActivo controladorActivo;
    ControladorSubCategoria controladorSub;
    ControladorCategoria controladorCategoria;
    ControladorVenta controladorVenta;
    ArrayList<Activo> listaActivo;
    int posicion = -1;
    Activo objeto;
    ArrayList<Movimiento> listaMovimiento;

    public ListaVentasRealizadas() {
        initComponents();
        setSize(900, 660);
        setLocationRelativeTo(null);

        listaActivo = new ArrayList<>();
        listaMovimiento=new ArrayList<>();
        modelo();
        controladorActivo = new ControladorActivo();
        controladorSub = new ControladorSubCategoria();
        controladorCategoria = new ControladorCategoria();
        controladorVenta = new ControladorVenta();
        
        listaMovimiento = controladorVenta.obtenerListaMovimiento();
        
        llenarCombo();
        verTabla();
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                verTabla();
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
                verTabla();
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
        Tabla.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Ver(e); //To change body of generated methods, choose Tools | Templates.
            }

        });

    }

    private void modelo() {

        modelo = new DefaultTableModel();
        modelo.addColumn("N°");
        modelo.addColumn("CODIGO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("SUBCATEGORIA");
        modelo.addColumn("MOVIMIENTO");
        modelo.addColumn("VENTA $");
        Tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboMovimiento = new javax.swing.JComboBox<>();
        BtnVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LISTA DE VENTAS REALIZADAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MOVIMIENTO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 110, 30));

        comboMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(comboMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 310, 30));

        BtnVer.setBackground(new java.awt.Color(0, 153, 0));
        BtnVer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnVer.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer.setText("VER");
        BtnVer.setEnabled(false);
        BtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, 30));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 850, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 970, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed
        // TODO add your handling code here:
        DetalleActivoFijo vista = new DetalleActivoFijo();
        vista.setVisible(true);
    }//GEN-LAST:event_BtnVerActionPerformed

    private void comboMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovimientoActionPerformed
        // TODO add your handling code here:
        modelo();
        if (comboMovimiento.getSelectedIndex() == 0) {
            verTabla();
        } else {
            verTablaCondicionada(comboMovimiento.getSelectedItem().toString());
        }
    }//GEN-LAST:event_comboMovimientoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVer;
    private javax.swing.JTable Tabla;
    private javax.swing.JComboBox<String> comboMovimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void Ver(MouseEvent e) {
        int row = Tabla.rowAtPoint(e.getPoint());
        posicion = Integer.parseInt(Tabla.getValueAt(row, 0).toString());
        objeto = new Activo();
        objeto = listaActivo.get(posicion - 1);
        BtnVer.setEnabled(true);
        

    }
    
    private void llenarCombo() {
        comboMovimiento.addItem("SELECCIONE");
        for (int i = 0; i < listaMovimiento.size(); i++) {
            comboMovimiento.addItem(listaMovimiento.get(i).getNombre());
        }
    }

    void verTabla() {
        //objeto = new Categoria();
        SimpleDateFormat forma=new SimpleDateFormat("dd-MM-YYYY");
        listaActivo = new ArrayList<>();
        listaActivo = controladorVenta.obtenerListaVentas();

        modelo.setRowCount(listaActivo.size());

        for (int i = 0; i < listaActivo.size(); i++) {

            modelo.setValueAt(i + 1, i, 0);
            modelo.setValueAt(listaActivo.get(i).getCodigo(), i, 1);
            modelo.setValueAt(listaActivo.get(i).getDescripcion(), i, 2);
            modelo.setValueAt(listaActivo.get(i).getCat(), i, 3);
            modelo.setValueAt(listaActivo.get(i).getSub(), i, 4);
            modelo.setValueAt(forma.format(listaActivo.get(i).getFecha()), i, 5);
            modelo.setValueAt(listaActivo.get(i).getPrecioVenta(), i, 6);
        }
        Tabla.setModel(modelo);
    }

    private void verTablaCondicionada(String estado) {
        SimpleDateFormat forma=new SimpleDateFormat("dd-MM-YYYY");
        listaActivo = new ArrayList<>();
        listaActivo = controladorVenta.obtenerListaVentasCondicionada(estado);

        modelo.setRowCount(listaActivo.size());

        for (int i = 0; i < listaActivo.size(); i++) {

            modelo.setValueAt(i + 1, i, 0);
            modelo.setValueAt(listaActivo.get(i).getCodigo(), i, 1);
            modelo.setValueAt(listaActivo.get(i).getDescripcion(), i, 2);
            modelo.setValueAt(listaActivo.get(i).getCat(), i, 3);
            modelo.setValueAt(listaActivo.get(i).getSub(), i, 4);
            modelo.setValueAt(forma.format(listaActivo.get(i).getFecha()), i, 5);
            modelo.setValueAt(listaActivo.get(i).getPrecioVenta(), i, 6);
        }
        Tabla.setModel(modelo);
    }

}
