/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAmortizacion;
import Controlador.ControladorPrestamo;
import Modelo.Amortizacion;
import Modelo.Cliente;
import Modelo.Prestamo;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class ListaAmortizacion extends javax.swing.JFrame {

    /**
     * Creates new form Amortizacion
     */
    DefaultTableModel modelo;
    ControladorAmortizacion controladorAmortizacion;
    ArrayList<Amortizacion> listaAmortizacion;
    ControladorPrestamo controladorPrestamo;
    Prestamo prestamo;
    Amortizacion objeto;
    SimpleDateFormat formatFecha;
    DecimalFormat forma;
    int posicion = -1;
    Cliente cliente;
    Double cuota = -1.0;

    public ListaAmortizacion(Prestamo obj, Cliente cli) {
        initComponents();
        setLocationRelativeTo(null);
        prestamo = obj;
        cliente = cli;
        modelo = new DefaultTableModel();
        controladorAmortizacion = new ControladorAmortizacion();
        controladorPrestamo = new ControladorPrestamo();

        formatFecha = new SimpleDateFormat("dd-MM-YYYY");
        forma = new DecimalFormat("0.00");

        modelo();
        verTabla();
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                verTabla();
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
                verTabla();
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
        Tabla.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Ver(e); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }

    private void modelo() {

        modelo = new DefaultTableModel();
        modelo.addColumn("N°");
        modelo.addColumn("FECHA");
        modelo.addColumn("SALDO INICIAL");
        modelo.addColumn("AMORTIZACION");
        modelo.addColumn("INTERESES");
        modelo.addColumn("CUOTA");
        modelo.addColumn("SALDO FINAL");
        modelo.addColumn("ESTADO");
        Tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnPagar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRefinanciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 660));
        setMinimumSize(new java.awt.Dimension(900, 660));
        setPreferredSize(new java.awt.Dimension(900, 660));
        getContentPane().setLayout(null);

        lblCuota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCuota.setForeground(new java.awt.Color(255, 255, 255));
        lblCuota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCuota.setInheritsPopupMenu(false);
        lblCuota.setPreferredSize(new java.awt.Dimension(930, 690));
        getContentPane().add(lblCuota);
        lblCuota.setBounds(70, 80, 720, 70);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(58, 154, 739, 380);

        btnPagar.setBackground(new java.awt.Color(255, 51, 51));
        btnPagar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("PAGAR CUOTA");
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagar);
        btnPagar.setBounds(370, 560, 210, 50);

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CERRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 560, 190, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CUADRO DE AMORTIZACION");
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setPreferredSize(new java.awt.Dimension(930, 690));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(229, 0, 400, 70);

        btnRefinanciar.setBackground(new java.awt.Color(0, 0, 255));
        btnRefinanciar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRefinanciar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefinanciar.setText("REFINANCIAR");
        btnRefinanciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefinanciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefinanciar);
        btnRefinanciar.setBounds(130, 560, 210, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        if (objeto.getEstado() == 0 && cliente.getEstado() == 1) {
            if (controladorAmortizacion.ModificarEstado(cuota, 1, objeto.getId())) {
                verTabla();
                objeto.setEstado(1);
                btnPagar.setBackground(Color.GREEN);
                btnPagar.setText("CUOTA CANCELADA");
                JOptionPane.showMessageDialog(null, "CUOTA CANCELADA", "EXITOSO", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "EL CLIENTE DEBE DE ESTAR ACTIVO", "EXITOSO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnRefinanciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefinanciarActionPerformed
        // TODO add your handling code here:
        if (cliente.getEstado() == 0 || cliente.getCartera() == 2) {
            JOptionPane.showMessageDialog(null, "EL CLIENTE DEBE SER ACTIVO Y NO DEBE DE TENER CARTERA DE INCOBRABILIDAD");
        } else {
            if (prestamo.getEstado()==1) {
                JOptionPane.showMessageDialog(null, "EL PRESTAMO YA HA SIDO CANCELADO");
            } else {
                RegistrarRefinanciamiento vista = new RegistrarRefinanciamiento(cliente, prestamo, listaAmortizacion);
                vista.setVisible(true);
            }

        }
    }//GEN-LAST:event_btnRefinanciarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRefinanciar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuota;
    // End of variables declaration//GEN-END:variables

    private void Ver(MouseEvent e) {
        int row = Tabla.rowAtPoint(e.getPoint());
        posicion = Integer.parseInt(Tabla.getValueAt(row, 0).toString());
        objeto = new Amortizacion();
        objeto = listaAmortizacion.get(posicion - 1);
        btnPagar.setEnabled(true);

        if (objeto.getEstado() == 0) {
            btnPagar.setBackground(Color.RED);
            btnPagar.setText("CANCELAR CUOTA");

        } else {
            btnPagar.setBackground(Color.GREEN);
            btnPagar.setText("CUOTA CANCELADA");
        }

        if (objeto.getEstado() == 1) {
            lblCuota.setText("CUOTA CANCELADA    CUOTA: $" + forma.format(objeto.getCuota()));
        } else {
            if (objeto.getMora() == 1) {
                cuota = objeto.getCuotaMensual() + objeto.getCuotaMensual() * 0.15;// si se quiere en la bd se puede meter taza de mora
                lblCuota.setText("CUOTA CON MORA    CUOTA A CANCELAR: $" + forma.format(cuota));
            } else {
                cuota = objeto.getCuotaMensual();
                lblCuota.setText("CUOTA PENDIENTE    CUOTA A CANCELAR: $" + forma.format(cuota));
            }

        }

    }

    void verTabla() {

        listaAmortizacion = new ArrayList<>();
        listaAmortizacion = controladorAmortizacion.obtenerLista(prestamo.getId());

        cambiarEstado();

        modelo.setRowCount(listaAmortizacion.size());

        for (int i = 0; i < listaAmortizacion.size(); i++) {

            modelo.setValueAt(i + 1, i, 0);
            modelo.setValueAt(formatFecha.format(listaAmortizacion.get(i).getFecha()), i, 1);
            modelo.setValueAt(forma.format(listaAmortizacion.get(i).getSaldoInicial()), i, 2);
            modelo.setValueAt(forma.format(listaAmortizacion.get(i).getAmortizacion()), i, 3);
            modelo.setValueAt(forma.format(listaAmortizacion.get(i).getInteres()), i, 4);
            modelo.setValueAt(forma.format(listaAmortizacion.get(i).getCuotaMensual()), i, 5);
            modelo.setValueAt(forma.format(Math.abs(listaAmortizacion.get(i).getSaldoFinal())), i, 6);
            if (listaAmortizacion.get(i).getEstado() == 0) {
                modelo.setValueAt("PENDIENTE", i, 7);
            } else {
                modelo.setValueAt("CANCELADO", i, 7);
            }

        }

        Tabla.setModel(modelo);
    }

    private void cambiarEstado() {
        int bandera = 0;
        for (int i = 0; i < listaAmortizacion.size(); i++) {
            if (listaAmortizacion.get(i).getEstado() == 0) {
                bandera = 1;
            }
        }

        if (bandera == 0) {
            controladorPrestamo.ModificarEstado(prestamo.getId());
        }
    }

}
