/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCliente;
import Modelo.Cliente;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class ModificarClientes extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarClientes
     */
    SimpleDateFormat forma;
    ControladorCliente controladorCliente;
    Cliente cliente;
    String duiAux, nitAux;

    public ModificarClientes(Cliente obj) {
        initComponents();
        setSize(900, 660);
        setLocationRelativeTo(null);
        forma = new SimpleDateFormat("dd-MM-YYYY");

        controladorCliente = new ControladorCliente();
        cliente = obj;
        duiAux = cliente.getDui();
        nitAux = cliente.getNit();

        CajaNombre.setText(cliente.getNombre());
        CajaApellidos.setText(cliente.getApellidos_Representante());
        CajaNit.setText(cliente.getNit());
        CajaDUI.setText(cliente.getDui());
        CajaTel.setText(cliente.getTelefono());
        CajaOcupacion.setText(cliente.getOcupacion());
        Direccion.setText(cliente.getDireccion());

        posicionarCombo();
        
        if(cliente.getTipo()==0){
            comboTipo.setSelectedIndex(0);
        }else{
            comboTipo.setSelectedIndex(1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CajaApellidos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        TxtApellidos = new javax.swing.JLabel();
        comboDepartamento = new javax.swing.JComboBox<>();
        TxtDui = new javax.swing.JLabel();
        TxtNit = new javax.swing.JLabel();
        CajaDUI = new javax.swing.JTextField();
        CajaNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        Txt = new javax.swing.JLabel();
        TxtOcupacion = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        CajaOcupacion = new javax.swing.JTextField();
        CajaNit = new javax.swing.JTextField();
        Txt2 = new javax.swing.JLabel();
        CajaTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Direccion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CajaNombre2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);
        getContentPane().add(CajaApellidos);
        CajaApellidos.setBounds(500, 180, 200, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 80, 930, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUEVO CLIENTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 310, 70);

        TxtApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtApellidos.setForeground(new java.awt.Color(255, 255, 255));
        TxtApellidos.setText("APELLIDOS");
        getContentPane().add(TxtApellidos);
        TxtApellidos.setBounds(540, 150, 130, 30);

        comboDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGUACHAPAN", "SONSONATE", "SANTA ANA", "SAN SALVADOR", "CHALATENANGO", "CUSCATLAN", "CABAÑAS", "LA LIBERTAD", "LA PAZ", "SAN VICENTE", "USUALUTAN", "SAN MIGUEL", "MARAZAN", "LA UNION" }));
        getContentPane().add(comboDepartamento);
        comboDepartamento.setBounds(560, 320, 200, 30);

        TxtDui.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtDui.setForeground(new java.awt.Color(255, 255, 255));
        TxtDui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtDui.setText("DUI");
        getContentPane().add(TxtDui);
        TxtDui.setBounds(520, 220, 130, 30);

        TxtNit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtNit.setText("NIT");
        getContentPane().add(TxtNit);
        TxtNit.setBounds(120, 220, 130, 30);
        getContentPane().add(CajaDUI);
        CajaDUI.setBounds(500, 260, 200, 30);
        getContentPane().add(CajaNombre);
        CajaNombre.setBounds(90, 180, 200, 30);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("NOMBRE DEL CLIENTE");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(130, 150, 130, 30);

        Txt.setBackground(new java.awt.Color(0, 51, 51));
        Txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Txt.setForeground(new java.awt.Color(255, 255, 255));
        Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt.setText("DEPARTAMENTO");
        getContentPane().add(Txt);
        Txt.setBounds(440, 320, 130, 30);

        TxtOcupacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtOcupacion.setForeground(new java.awt.Color(255, 255, 255));
        TxtOcupacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtOcupacion.setText("OCUPACION");
        getContentPane().add(TxtOcupacion);
        TxtOcupacion.setBounds(0, 390, 130, 30);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERSONA NATURAL", "PERSONA JURIDICA" }));
        comboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoItemStateChanged(evt);
            }
        });
        getContentPane().add(comboTipo);
        comboTipo.setBounds(140, 100, 200, 30);
        getContentPane().add(CajaOcupacion);
        CajaOcupacion.setBounds(100, 390, 200, 30);
        getContentPane().add(CajaNit);
        CajaNit.setBounds(90, 260, 200, 30);

        Txt2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Txt2.setForeground(new java.awt.Color(255, 255, 255));
        Txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt2.setText("TELEFONO");
        getContentPane().add(Txt2);
        Txt2.setBounds(0, 320, 130, 30);
        getContentPane().add(CajaTel);
        CajaTel.setBounds(100, 320, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIRECCION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 390, 100, 30);

        Direccion.setColumns(20);
        Direccion.setRows(5);
        jScrollPane1.setViewportView(Direccion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 380, 230, 83);

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 480, 110, 30);

        botonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar);
        botonRegistrar.setBounds(60, 480, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TIPO DE CLIENTE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 100, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 920, 680);
        getContentPane().add(CajaNombre2);
        CajaNombre2.setBounds(80, 180, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            String nombre = CajaNombre.getText();
            String apellidos_Representante = CajaApellidos.getText();
            String nit = CajaNit.getText();
            String dui_Representante = CajaDUI.getText();
            String telefono = CajaTel.getText();
            String departamento = comboDepartamento.getSelectedItem().toString();
            String ocupacion = CajaOcupacion.getText();
            String direcion = Direccion.getText();

            Integer tipo = comboTipo.getSelectedIndex();

            // Cliente cliente = new Cliente(nombre, apellidos_Representante, dui_Representante, nit, telefono,
            //ocupacion, departamento, fecha, direcion, tipo);
            cliente.setNombre(nombre);
            cliente.setApellidos_Representante(apellidos_Representante);
            cliente.setDui(dui_Representante);
            cliente.setNit(nit);
            cliente.setTelefono(telefono);
            cliente.setOcupacion(ocupacion);
            cliente.setDepartmento(departamento);
            cliente.setDireccion(direcion);
            cliente.setTipo(tipo);

            if (dui_Representante.equals(duiAux) || nit.equals(nitAux)) {
                controladorCliente.Modificar(cliente);
                JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS", "EXITOSO", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {

                if (controladorCliente.existeNit(nit)) {

                    if (controladorCliente.existeDui(dui_Representante)) {
                        controladorCliente.Modificar(cliente);
                        JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS", "EXITOSO", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "YA EXISTE UN CLIENTE CON ESTE NUMERO DE DUI", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "YA EXISTE UN CLIENTE CON ESTE NUMERO DE NIT", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "COMPLETE CAMPOS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoItemStateChanged
        // TODO add your handling code here:
        if (comboTipo.getSelectedIndex() == 0) {
            lblNombre.setText("NOMBRE DEL CLIENTE");
            TxtApellidos.setText("APELLIDOS");
            TxtNit.setText("NIT");
            TxtDui.setText("DUI");
            TxtOcupacion.setText("OCUPACION");

        } else if (comboTipo.getSelectedIndex() == 1) {
            lblNombre.setText("NOMBRE DE LA EMPRESA");
            TxtApellidos.setText("REPRESENTANTE LEGAL");
            TxtNit.setText("NIT DE LA EMPRESA");
            TxtDui.setText("DUI DEL REPESENTANTE");
            TxtOcupacion.setText("GIRO");
        }
    }//GEN-LAST:event_comboTipoItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistrarClientes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaApellidos;
    private javax.swing.JTextField CajaDUI;
    private javax.swing.JTextField CajaNit;
    private javax.swing.JTextField CajaNombre;
    private javax.swing.JTextField CajaNombre2;
    private javax.swing.JTextField CajaOcupacion;
    private javax.swing.JTextField CajaTel;
    private javax.swing.JTextArea Direccion;
    private javax.swing.JLabel Txt;
    private javax.swing.JLabel Txt2;
    private javax.swing.JLabel TxtApellidos;
    private javax.swing.JLabel TxtDui;
    private javax.swing.JLabel TxtNit;
    private javax.swing.JLabel TxtOcupacion;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JComboBox<String> comboDepartamento;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

    private boolean validar() {
        if (CajaNombre.getText().equals("") || CajaApellidos.getText().equals("")) {
            return false;
        } else if (CajaNit.getText().equals("") || CajaDUI.getText().equals("")) {
            return false;
        } else if (CajaTel.getText().equals("") || CajaOcupacion.getText().equals("")) {
            return false;
        } else if (Direccion.getText().equals("")) {
            return false;
        }
        return true;
    }

    private void posicionarCombo() {
        if (cliente.getDepartmento().equals("AGUACHAPAN")) {
            comboDepartamento.setSelectedIndex(0);
        } else if (cliente.getDepartmento().equals("SONSONATE")) {
            comboDepartamento.setSelectedIndex(1);
        } else if (cliente.getDepartmento().equals("SANTA ANA")) {
            comboDepartamento.setSelectedIndex(2);
        } else if (cliente.getDepartmento().equals("SAN SALVADOR")) {
            comboDepartamento.setSelectedIndex(3);
        } else if (cliente.getDepartmento().equals("CHALATENANGO")) {
            comboDepartamento.setSelectedIndex(4);
        } else if (cliente.getDepartmento().equals("CUSCATLAN")) {
            comboDepartamento.setSelectedIndex(5);
        } else if (cliente.getDepartmento().equals("CABAÑAS")) {
            comboDepartamento.setSelectedIndex(6);
        } else if (cliente.getDepartmento().equals("LA LIBERTAD")) {
            comboDepartamento.setSelectedIndex(7);
        } else if (cliente.getDepartmento().equals("LA PAZ")) {
            comboDepartamento.setSelectedIndex(8);
        } else if (cliente.getDepartmento().equals("SAN VICENTE")) {
            comboDepartamento.setSelectedIndex(9);
        } else if (cliente.getDepartmento().equals("USUALUTAN")) {
            comboDepartamento.setSelectedIndex(10);
        } else if (cliente.getDepartmento().equals("SAN MIGUEL")) {
            comboDepartamento.setSelectedIndex(11);
        } else if (cliente.getDepartmento().equals("MORAZAN")) {
            comboDepartamento.setSelectedIndex(12);
        } else if (cliente.getDepartmento().equals("LA UNION")) {
            comboDepartamento.setSelectedIndex(13);
        }
    }
}
