/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCategoria;
import Controlador.ControladorSubCategoria;
import Modelo.Categoria;
import Modelo.SubCategoria;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author PEREZ
 */
public class ModificarSubCategoria extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCategoria
     */
    ControladorCategoria controladorCategoria;
    ControladorSubCategoria cs;
    ArrayList<Categoria> listaCategoria;
    SubCategoria sc;

    public ModificarSubCategoria(SubCategoria sc) {
        initComponents();
        setLocationRelativeTo(null);
        this.sc = sc;
        controladorCategoria = new ControladorCategoria();
        cs = new ControladorSubCategoria();
        listaCategoria = new ArrayList<>();
        listaCategoria = controladorCategoria.obtenerCuentas();
        llenarCombo();
        this.CajaNombre.setText(sc.getNombre());
        this.CajaCod.setText(sc.getCodigo());
    }

    public void llenarCombo() {
        ComboCategoria.addItem("SELECCIONE");
        for (int i = 0; i < listaCategoria.size(); i++) {
            ComboCategoria.addItem(listaCategoria.get(i).getNombre());
            if (listaCategoria.get(i).getIdCategoria().equals(sc.getIdCtegoria())) {
                ComboCategoria.setSelectedItem(listaCategoria.get(i).getNombre());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtNombre = new javax.swing.JLabel();
        CajaNombre = new javax.swing.JTextField();
        TxtNombre1 = new javax.swing.JLabel();
        CajaCod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        TxtNombre2 = new javax.swing.JLabel();
        ComboCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MODIFICAR SUBCATEGORIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 410, 70));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 930, 20));

        TxtNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNombre.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre.setText("NOMBRE");
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, 30));
        getContentPane().add(CajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 200, 30));

        TxtNombre1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNombre1.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre1.setText("CODIGO");
        getContentPane().add(TxtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, 30));
        getContentPane().add(CajaCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, 30));

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 110, 30));

        botonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Guardar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 110, 30));

        TxtNombre2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNombre2.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre2.setText("CATEGORIA");
        getContentPane().add(TxtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, 30));

        getContentPane().add(ComboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 200, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 920, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String nombre = this.CajaNombre.getText();
        String cod = this.CajaCod.getText();
        int val = ComboCategoria.getSelectedIndex();
        if (vacio(nombre, val, cod)) {
            int cat = listaCategoria.get(val - 1).getIdCategoria();
            if (cs.existeCampo("codigo", cod, sc.getIdSubcategoria()) && cs.existeCampo("nombre", nombre, sc.getIdSubcategoria())) {
                sc.setCodigo(cod);
                sc.setNombre(nombre);
                sc.setIdCtegoria(cat);
                if (cs.ModificarSubCategoria(sc)) {
                    JOptionPane.showMessageDialog(rootPane, "SUBCATEGORIA MODIFICADA EXITOSAMENTE", "MODIFICAR SUBCATEGORIA", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERROR AL MODIFICAR CATEGORIA!", "MODIFICAR SUBCATEGORIA", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                mensajes(cod, nombre);
            }
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaCod;
    private javax.swing.JTextField CajaNombre;
    private javax.swing.JComboBox<String> ComboCategoria;
    private javax.swing.JLabel TxtNombre;
    private javax.swing.JLabel TxtNombre1;
    private javax.swing.JLabel TxtNombre2;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private boolean vacio(String nombre, int val, String cod) {
        if (nombre.isEmpty() || val == 0 || cod.isEmpty()
                || nombre.equalsIgnoreCase(" ") || cod.equalsIgnoreCase(" ")) {
            JOptionPane.showMessageDialog(rootPane, "COMPLETE LOS CAMPOS VACIOS", "MODIFICAR CATEGORIA", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void mensajes(String cod, String nombre) {
        if (!cs.existeCampo("codigo", cod, sc.getIdSubcategoria()) && cs.existeCampo("nombre", nombre, sc.getIdSubcategoria())) {
            JOptionPane.showMessageDialog(rootPane, "CODIGO: " + cod + ", YA SE ENCUENTRA REGISTRADO", "MODIFICAR SUBCATEGORIA", JOptionPane.WARNING_MESSAGE);
        } else if (cs.existeCampo("codigo", cod, sc.getIdSubcategoria()) && !cs.existeCampo("nombre", nombre, sc.getIdSubcategoria())) {
            JOptionPane.showMessageDialog(rootPane, "NOMBRE: " + nombre + ", YA SE ENCUENTRA REGISTRADO", "MODIFICAR SUBCATEGORIA", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "CODIGO: " + cod + " Y NOMBRE: " + nombre + ", YA SE ENCUENTRAN REGISTRADOS", "MODIFICAR SUBCATEGORIA", JOptionPane.WARNING_MESSAGE);
        }
    }
}
