/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorActivo;
import Controlador.ControladorCategoria;
import Controlador.ControladorDeparamento;
import Controlador.ControladorMarca;
import Controlador.ControladorProveedor;
import Controlador.ControladorSubCategoria;
import Modelo.Activo;
import Modelo.Categoria;
import Modelo.Departamento;
import Modelo.DetalleActivo;
import Modelo.Marca;
import Modelo.Proveedor;
import Modelo.SubCategoria;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class RegistrarActivoFijo extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarClientes
     */
    ControladorCategoria controladorCategoria;
    ControladorSubCategoria controladorSub;
    ControladorDeparamento controladorDeparamento;
    ControladorProveedor controladorProveedor;
    ControladorMarca controladorMarca;
    ControladorActivo controladoActivo;

    ArrayList<Categoria> listaCategoria;
    ArrayList<SubCategoria> listaSubCategoria;
    ArrayList<Departamento> listaDepartamento;
    ArrayList<Proveedor> listaProveedor;
    ArrayList<Marca> listaMarca;

    public RegistrarActivoFijo() {
        initComponents();
        setSize(900, 660);
        setLocationRelativeTo(null);

        controladorCategoria = new ControladorCategoria();
        controladorSub = new ControladorSubCategoria();
        controladorDeparamento = new ControladorDeparamento();
        controladorProveedor = new ControladorProveedor();
        controladorMarca = new ControladorMarca();
        controladoActivo = new ControladorActivo();

        listaCategoria = new ArrayList<>();
        listaSubCategoria = new ArrayList<>();
        listaDepartamento = new ArrayList<>();
        listaProveedor = new ArrayList<>();
        listaMarca = new ArrayList<>();

        listaCategoria = controladorCategoria.obtenerCuentas();
        listaDepartamento = controladorDeparamento.obtenerLista();
        listaProveedor = controladorProveedor.obtenerListaActivo();

        CajaVidaUilR.setEnabled(false);
        cajaFecha.setMaxSelectableDate(new Date());
        cajaFecha.setEnabled(false);
        llenarComboCategoria();
        llenarComboDep();
        llenarComboPro();

        generarCodigo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNit = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        CajaCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        comboSub = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboDepartamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboProveedor = new javax.swing.JComboBox<>();
        TxtNit1 = new javax.swing.JLabel();
        CajaSerie = new javax.swing.JTextField();
        TxtNit2 = new javax.swing.JLabel();
        CajaPrecio = new javax.swing.JTextField();
        comboCondicion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TxtNit4 = new javax.swing.JLabel();
        TxtNit3 = new javax.swing.JLabel();
        cajaFecha = new com.toedter.calendar.JDateChooser();
        chectDonado = new javax.swing.JCheckBox();
        TxtNit5 = new javax.swing.JLabel();
        CajaVidaUilR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 930, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUEVO ACTIVO FIJO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CATEGORIA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        TxtNit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit.setText("CODIGO");
        getContentPane().add(TxtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 30));

        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 30));
        getContentPane().add(CajaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DESCRIPCION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 100, 30));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 200, 100));

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 100, 30));

        botonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 110, 30));

        getContentPane().add(comboSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SUBCATEGORIA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 130, 30));

        getContentPane().add(comboDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEPARTAMENTO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MARCA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 30));

        getContentPane().add(comboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PROVEEDOR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 130, 30));

        comboProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(comboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 200, 30));

        TxtNit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit1.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit1.setText("SERIE/MARCA");
        getContentPane().add(TxtNit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 130, 30));
        getContentPane().add(CajaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 200, 30));

        TxtNit2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit2.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit2.setText("PRECIO");
        getContentPane().add(TxtNit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 130, 30));
        getContentPane().add(CajaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 200, 30));

        comboCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "NUEVO", "USADO" }));
        comboCondicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCondicionActionPerformed(evt);
            }
        });
        getContentPane().add(comboCondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CONDICION");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 130, 30));

        TxtNit4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit4.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit4.setText("INICIO DE USO");
        getContentPane().add(TxtNit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 30));

        TxtNit3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit3.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit3.setText("DOCANCION");
        getContentPane().add(TxtNit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 130, 30));

        cajaFecha.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(cajaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 200, 30));

        chectDonado.setBackground(new java.awt.Color(102, 102, 102));
        chectDonado.setForeground(new java.awt.Color(255, 255, 255));
        chectDonado.setText("DONADO");
        getContentPane().add(chectDonado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        TxtNit5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit5.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit5.setText("VIDA UTIL RESTANTE");
        getContentPane().add(TxtNit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 130, 30));
        getContentPane().add(CajaVidaUilR, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 200, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 920, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:

        String donado = "";
        String codigo = CajaCodigo.getText();
        String descripcion = this.descripcion.getText();
        int idSubCategoria = listaSubCategoria.get(comboSub.getSelectedIndex() - 1).getIdSubcategoria();
        int idDepartamento = listaDepartamento.get(comboDepartamento.getSelectedIndex() - 1).getIdDep();
        int idMarca = listaMarca.get(comboMarca.getSelectedIndex() - 1).getIdM();
        String condicion = comboCondicion.getSelectedItem().toString();
        String serie = CajaSerie.getText();
        Double precio = Double.parseDouble(CajaPrecio.getText());
        Date fecha = cajaFecha.getDate();
        Integer vidautilrestante = null;

        if (CajaVidaUilR.getText().equals("")) {
            vidautilrestante = listaCategoria.get(comboCategoria.getSelectedIndex() - 1).getVidaUtil();
        } else {
            vidautilrestante = Integer.parseInt(CajaVidaUilR.getText());
        }

        if (chectDonado.isSelected()) {
            donado = "SI";
        } else {
            donado = "NO";
        }

        if (true) {
            Activo x = new Activo(codigo, descripcion, idDepartamento, idSubCategoria, idMarca, "", 0);
            controladoActivo.Agregar(x);
            x.setId(controladoActivo.obtenerUltimoRegistro());
            DetalleActivo y = new DetalleActivo(serie, new Date(), fecha, precio, donado, vidautilrestante, x, condicion);
            controladoActivo.AgregarDetalle(y);
            JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS");
            
           
        } else {

        }

       

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here:
        listaSubCategoria = new ArrayList<SubCategoria>();
        int indice = comboCategoria.getSelectedIndex() - 1;
        comboSub.removeAllItems();

        if (indice != -1) {
            listaSubCategoria = controladorSub.obtenerListaFiltrada(listaCategoria.get(indice).getIdCategoria());
            llenaComboSub();
        } else {
            comboSub.addItem("SELECCIONE");
        }

    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void comboProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProveedorActionPerformed
        // TODO add your handling code here:
        listaMarca = new ArrayList<>();
        int indice = comboProveedor.getSelectedIndex() - 1;
        comboMarca.removeAllItems();

        if (indice != -1) {
            listaMarca = controladorMarca.obtenerListaFiltrada(listaCategoria.get(indice).getIdCategoria());
            llenarComboMarca();
        } else {
            comboMarca.addItem("SELECCIONE");
        }
    }//GEN-LAST:event_comboProveedorActionPerformed

    private void comboCondicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCondicionActionPerformed
        // TODO add your handling code here:
        Date fecha = new Date();
        cajaFecha.setDate(null);
        CajaVidaUilR.setText("");
        if (comboCondicion.getSelectedIndex() == 0) {
            cajaFecha.setEnabled(false);
            CajaVidaUilR.setEnabled(false);
        } else if (comboCondicion.getSelectedIndex() == 1) {
            cajaFecha.setEnabled(false);
            cajaFecha.setDate(fecha);
            CajaVidaUilR.setEnabled(false);
        } else if (comboCondicion.getSelectedIndex() == 2) {
            cajaFecha.setEnabled(true);
            CajaVidaUilR.setEnabled(true);
        }
    }//GEN-LAST:event_comboCondicionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistrarClientes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaCodigo;
    private javax.swing.JTextField CajaPrecio;
    private javax.swing.JTextField CajaSerie;
    private javax.swing.JTextField CajaVidaUilR;
    private javax.swing.JLabel TxtNit;
    private javax.swing.JLabel TxtNit1;
    private javax.swing.JLabel TxtNit2;
    private javax.swing.JLabel TxtNit3;
    private javax.swing.JLabel TxtNit4;
    private javax.swing.JLabel TxtNit5;
    private javax.swing.JButton botonRegistrar;
    private com.toedter.calendar.JDateChooser cajaFecha;
    private javax.swing.JCheckBox chectDonado;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboCondicion;
    private javax.swing.JComboBox<String> comboDepartamento;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JComboBox<String> comboSub;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void llenarComboCategoria() {
        comboCategoria.addItem("SELECCIONE");
        for (int i = 0; i < listaCategoria.size(); i++) {
            comboCategoria.addItem(listaCategoria.get(i).getNombre());
        }
    }

    private void llenaComboSub() {
        comboSub.addItem("SELECCIONE");
        for (int i = 0; i < listaSubCategoria.size(); i++) {
            comboSub.addItem(listaSubCategoria.get(i).getNombre());
        }
    }

    private void llenarComboDep() {
        comboDepartamento.addItem("SELECCIONE");
        for (int i = 0; i < listaDepartamento.size(); i++) {
            comboDepartamento.addItem(listaDepartamento.get(i).getNombreDep());
        }
    }

    private void llenarComboPro() {
        comboProveedor.addItem("SELECCIONE");
        for (int i = 0; i < listaProveedor.size(); i++) {
            comboProveedor.addItem(listaProveedor.get(i).getNombre());
        }
    }

    private void llenarComboMarca() {
        comboMarca.addItem("SELECCIONE");
        for (int i = 0; i < listaMarca.size(); i++) {
            comboMarca.addItem(listaMarca.get(i).getNombre());
        }
    }

    private void generarCodigo() {
        ArrayList<Activo> lista = controladoActivo.obtenerCodigo();
        DecimalFormat format = new DecimalFormat("0000");
        int cantidad = lista.size() + 1;
        String codi = "" + format.format(cantidad);
        CajaCodigo.setText(codi);
        CajaCodigo.setEnabled(false);
    }
}
