/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCategoria;
import Modelo.Categoria;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author PEREZ
 */
public class RegistrarCategoria extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCategoria
     */
    ControladorCategoria controlador = new ControladorCategoria();

    public RegistrarCategoria() {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new ControladorCategoria();
        CajaCodigo.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtNombre = new javax.swing.JLabel();
        CajaNombre = new javax.swing.JTextField();
        TxtVidaUtil = new javax.swing.JLabel();
        CajaVidaUtil = new javax.swing.JTextField();
        TxtNombre1 = new javax.swing.JLabel();
        CajaCodigo = new javax.swing.JTextField();
        TxtNombre2 = new javax.swing.JLabel();
        CajaValorResidual = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUEVA CATEGORIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 70));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 930, 20));

        TxtNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNombre.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre.setText("NOMBRE");
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, 30));
        getContentPane().add(CajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 200, 30));

        TxtVidaUtil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtVidaUtil.setForeground(new java.awt.Color(255, 255, 255));
        TxtVidaUtil.setText("VIDA UTIL");
        getContentPane().add(TxtVidaUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 130, 30));
        getContentPane().add(CajaVidaUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 200, 30));

        TxtNombre1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNombre1.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre1.setText("CODIGO");
        getContentPane().add(TxtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 130, 30));
        getContentPane().add(CajaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 200, 30));

        TxtNombre2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNombre2.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre2.setText("VALOR RESIDUAL");
        getContentPane().add(TxtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 130, 30));
        getContentPane().add(CajaValorResidual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 200, 30));

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 100, 30));

        botonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 110, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GENERAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 920, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            String nombre = CajaNombre.getText();
            String codigo = CajaCodigo.getText();
            Integer vidaUtil = Integer.parseInt(CajaVidaUtil.getText());
            //Integer vidaEconomica = Integer.parseInt(CajaEconomica.getText());
            Double valorResidual = Double.parseDouble(CajaValorResidual.getText());

            Categoria categoria = new Categoria(nombre, codigo, vidaUtil, 0, valorResidual, 0);
            controlador.AgregarCatgoria(categoria);
            JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "COMPLETE CAMPOS", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (CajaNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DEBE DE AGREGAR UN NOMBRE A SU NUEVA CATEGORIA", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            String codigo = ObtenerCodigo(CajaNombre.getText());
            CajaCodigo.setText(codigo);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaCodigo;
    private javax.swing.JTextField CajaNombre;
    private javax.swing.JTextField CajaValorResidual;
    private javax.swing.JTextField CajaVidaUtil;
    private javax.swing.JLabel TxtNombre;
    private javax.swing.JLabel TxtNombre1;
    private javax.swing.JLabel TxtNombre2;
    private javax.swing.JLabel TxtVidaUtil;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private String ObtenerCodigo(String codigo) {
        ArrayList<Categoria> lista = controlador.obtenerCategoriaCaracter(codigo);
        DecimalFormat format = new DecimalFormat("0000");
        int cantidad = lista.size() + 1;
        String aux = "" + cantidad;
        String codi = "" + codigo.charAt(0) + codigo.charAt(1) + format.format(cantidad);

        return codi;
    }

    private void limpiar() {
        CajaCodigo.setText("");
        CajaNombre.setText("");
        CajaValorResidual.setText("");
        CajaVidaUtil.setText("");
    }

    private boolean validar() {
        if(CajaCodigo.getText().equals("") || CajaNombre.getText().equals("")){
            return false;
        }else if(CajaValorResidual.getText().equals("") || CajaVidaUtil.getText().equals("")){
            return false;
        }
        return true;
    }
}
