/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorActivo;
import Controlador.ControladorAmortizacion;
import Controlador.ControladorCliente;
import Controlador.ControladorCredito;
import Controlador.ControladorDepreciacion;
import Controlador.ControladorFiador;
import Controlador.ControladorPrestamo;
import Controlador.ControladorVenta;
import Modelo.Activo;
import Modelo.Amortizacion;
import Modelo.Cliente;
import Modelo.Credito;
import Modelo.Depreciacion;
import Modelo.DepreciacionAcumulada;
import Modelo.Fiador;
import Modelo.Movimiento;
import Modelo.Prestamo;
import Modelo.Venta;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class RegistrarRefinanciamiento extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarClientes
     */
    SimpleDateFormat formaFecha;
    Date fechaActual;
    ArrayList<Prestamo> listaPrestamos;
    DecimalFormat formaPrecio;
    int meses;
    ControladorCredito controladorCredito;
    ArrayList<Credito> listaCreditos;
    Cliente cliente;
    Double cuota = -1.00;
    Credito credito;
    ArrayList<Amortizacion> listaAmortizacion;
    ControladorPrestamo controladorPrestamo;
    ControladorAmortizacion controladorAmortizacion;
    ControladorCliente controladorCliente;
    ControladorFiador controladorFiador;
    Prestamo prestamo;
    ArrayList<Amortizacion> listaAux;

    public RegistrarRefinanciamiento(Cliente obj, Prestamo pres, ArrayList<Amortizacion> lis) {
        initComponents();

        cliente = obj;
        prestamo = pres;

        txtNombreFiador.setVisible(false);
        txtDuiFiador.setVisible(false);
        txtNitFiador.setVisible(false);
        txtFuente.setVisible(false);
        TxtDatos.setVisible(false);

        CajaNombreFiador.setVisible(false);
        CajaDuiFiador.setVisible(false);
        CajaNitFiador.setVisible(false);
        CajaFuente.setVisible(false);

        controladorCliente = new ControladorCliente();
        controladorCredito = new ControladorCredito();
        controladorPrestamo = new ControladorPrestamo();
        controladorAmortizacion = new ControladorAmortizacion();
        controladorFiador = new ControladorFiador();
        formaFecha = new SimpleDateFormat("dd-MM-YYYY");
        fechaActual = new Date();
        formaPrecio = new DecimalFormat("0.00");
        listaCreditos = new ArrayList<>();
        listaAmortizacion = new ArrayList<>();
        listaAux = new ArrayList<>();

        listaAux = lis;

        CajaFecha.setText(formaFecha.format(fechaActual));

        CajaDui.setText(cliente.getDui());
        CajaNombre.setText(cliente.getNombre());

        listaCreditos = controladorCredito.obtenerListaEstado(cliente.getTipo());
        llenarCombo();
        validarCombo();
        //Línea 1
        this.setSize(new Dimension(899, 660));

        //Línea 2
        this.setMinimumSize(new Dimension(899, 450));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CajaCuota = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        TxtApellidos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtDui = new javax.swing.JLabel();
        CajaFecha = new javax.swing.JTextField();
        CajaDui = new javax.swing.JTextField();
        TxtNombre2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        TxtDui1 = new javax.swing.JLabel();
        CajaNombre = new javax.swing.JTextField();
        CajaMonto = new javax.swing.JTextField();
        TxtDui2 = new javax.swing.JLabel();
        TxtDui3 = new javax.swing.JLabel();
        CajaPlazo = new javax.swing.JTextField();
        botonRegistrar1 = new javax.swing.JButton();
        Txt4 = new javax.swing.JLabel();
        comboFiador = new javax.swing.JComboBox<>();
        TxtDatos = new javax.swing.JLabel();
        txtNombreFiador = new javax.swing.JLabel();
        txtNitFiador = new javax.swing.JLabel();
        CajaNitFiador = new javax.swing.JTextField();
        CajaNombreFiador = new javax.swing.JTextField();
        txtDuiFiador = new javax.swing.JLabel();
        CajaDuiFiador = new javax.swing.JTextField();
        txtFuente = new javax.swing.JLabel();
        CajaFuente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(799, 342));
        getContentPane().setLayout(null);

        CajaCuota.setEnabled(false);
        getContentPane().add(CajaCuota);
        CajaCuota.setBounds(140, 280, 200, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 80, 930, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRAR REFINANCIAMIENTO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 420, 70);

        TxtApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtApellidos.setForeground(new java.awt.Color(255, 255, 255));
        TxtApellidos.setText("MONTO");
        getContentPane().add(TxtApellidos);
        TxtApellidos.setBounds(450, 170, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DUI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 110, 130, 30);

        TxtDui.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtDui.setForeground(new java.awt.Color(255, 255, 255));
        TxtDui.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtDui.setText("CUOTA");
        getContentPane().add(TxtDui);
        TxtDui.setBounds(70, 280, 110, 30);

        CajaFecha.setEnabled(false);
        getContentPane().add(CajaFecha);
        CajaFecha.setBounds(600, 230, 200, 30);

        CajaDui.setEnabled(false);
        getContentPane().add(CajaDui);
        CajaDui.setBounds(190, 110, 200, 30);

        TxtNombre2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNombre2.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombre2.setText("NOMBRE DEL CLIENTE");
        getContentPane().add(TxtNombre2);
        TxtNombre2.setBounds(450, 110, 120, 30);

        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboTipo);
        comboTipo.setBounds(190, 170, 200, 30);

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 580, 100, 30);

        botonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar);
        botonRegistrar.setBounds(580, 580, 110, 30);

        TxtDui1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtDui1.setForeground(new java.awt.Color(255, 255, 255));
        TxtDui1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtDui1.setText("FECHA DE REGISTRO");
        getContentPane().add(TxtDui1);
        TxtDui1.setBounds(430, 230, 160, 30);

        CajaNombre.setEnabled(false);
        getContentPane().add(CajaNombre);
        CajaNombre.setBounds(600, 110, 200, 30);
        getContentPane().add(CajaMonto);
        CajaMonto.setBounds(600, 170, 200, 30);

        TxtDui2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtDui2.setForeground(new java.awt.Color(255, 255, 255));
        TxtDui2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtDui2.setText("TIPO DE PRESTAMO");
        getContentPane().add(TxtDui2);
        TxtDui2.setBounds(40, 170, 160, 30);

        TxtDui3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtDui3.setForeground(new java.awt.Color(255, 255, 255));
        TxtDui3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtDui3.setText("PLAZO");
        getContentPane().add(TxtDui3);
        TxtDui3.setBounds(70, 230, 110, 30);
        getContentPane().add(CajaPlazo);
        CajaPlazo.setBounds(190, 230, 200, 30);

        botonRegistrar1.setBackground(new java.awt.Color(255, 204, 0));
        botonRegistrar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar1.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar1.setText("GENERAR CUOTA");
        botonRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar1);
        botonRegistrar1.setBounds(350, 280, 170, 33);

        Txt4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Txt4.setForeground(new java.awt.Color(255, 255, 255));
        Txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt4.setText("FIADOR");
        getContentPane().add(Txt4);
        Txt4.setBounds(530, 280, 130, 30);

        comboFiador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        comboFiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiadorActionPerformed(evt);
            }
        });
        getContentPane().add(comboFiador);
        comboFiador.setBounds(640, 280, 200, 30);

        TxtDatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtDatos.setForeground(new java.awt.Color(255, 255, 255));
        TxtDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtDatos.setText("DATOS DEL FIADOR");
        getContentPane().add(TxtDatos);
        TxtDatos.setBounds(310, 340, 270, 60);

        txtNombreFiador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNombreFiador.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreFiador.setText("NOMBRE DEL FIADOR");
        getContentPane().add(txtNombreFiador);
        txtNombreFiador.setBounds(30, 400, 130, 30);

        txtNitFiador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNitFiador.setForeground(new java.awt.Color(255, 255, 255));
        txtNitFiador.setText("NIT DEL FIADOR");
        getContentPane().add(txtNitFiador);
        txtNitFiador.setBounds(460, 400, 130, 30);
        getContentPane().add(CajaNitFiador);
        CajaNitFiador.setBounds(640, 400, 200, 30);
        getContentPane().add(CajaNombreFiador);
        CajaNombreFiador.setBounds(210, 400, 200, 30);

        txtDuiFiador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDuiFiador.setForeground(new java.awt.Color(255, 255, 255));
        txtDuiFiador.setText("DUI DEL FIADOR");
        getContentPane().add(txtDuiFiador);
        txtDuiFiador.setBounds(30, 460, 130, 30);
        getContentPane().add(CajaDuiFiador);
        CajaDuiFiador.setBounds(210, 460, 200, 30);

        txtFuente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFuente.setForeground(new java.awt.Color(255, 255, 255));
        txtFuente.setText("FUENTE DE INGRESOS");
        getContentPane().add(txtFuente);
        txtFuente.setBounds(460, 460, 130, 30);
        getContentPane().add(CajaFuente);
        CajaFuente.setBounds(640, 460, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 970, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:

        if (validar()) {

            String nombreFiador = CajaNombreFiador.getText();
            String duiFiador = CajaDuiFiador.getText();
            String nitFiador = CajaNitFiador.getText();
            String fuente = CajaFuente.getText();

            Integer idCliente = cliente.getId();
            Integer idCredito = listaCreditos.get(comboTipo.getSelectedIndex() - 1).getId();
            Double montoMin = listaCreditos.get(comboTipo.getSelectedIndex() - 1).getCantidadMin();
            Double montoMax = listaCreditos.get(comboTipo.getSelectedIndex() - 1).getCantidadMax();
            Double monto = Double.parseDouble(CajaMonto.getText());
            int plazoMax = listaCreditos.get(comboTipo.getSelectedIndex() - 1).getPlazoMax();
            int plazo = Integer.parseInt(CajaPlazo.getText());
            Double intereses = 0.00;
            Double saldoFinal = 0.00;
            Amortizacion amortizacion;
            Double in = listaCreditos.get(comboTipo.getSelectedIndex() - 1).getInteres() / 12;
            in = in / 100;
            Integer id_fiador = -1;

            if ((monto >= montoMin) && (monto <= montoMax) && (plazo >= 4) && (plazo <= plazoMax)) {

                controladorPrestamo.ModificarEstado(prestamo.getId());
                Double c = 0.0;
                for (int var = 0; var < listaAux.size(); var++) {
                    if (listaAux.get(var).getMora() == 1) {
                        c = listaAux.get(var).getCuotaMensual() + listaAux.get(var).getCuotaMensual() * 0.15;
                    } else {
                        c = listaAux.get(var).getCuotaMensual();
                    }
                    // JOptionPane.showMessageDialog(null, "" + c+" " + 1 + " " + listaAux.get(var).getId());
                    if (controladorAmortizacion.ModificarEstado(c, 1, listaAux.get(var).getId())) {
                    }
                }

                if (comboFiador.getSelectedIndex() == 1) {
                    Fiador fiador = new Fiador(nombreFiador, nitFiador, duiFiador, fuente);
                    controladorFiador.Agregar(fiador);
                    fiador.setId(controladorFiador.obtenerUltimoRegistro());
                    id_fiador = fiador.getId();
                }

                Prestamo x = new Prestamo(monto, plazo, fechaActual, cuota, idCliente, idCredito);
                if (id_fiador != -1) {
                    x.setIdFiador(id_fiador);
                    controladorPrestamo.AgregarConF(x);
                } else {
                    controladorPrestamo.Agregar(x);
                }

                x.setId(controladorPrestamo.obtenerUltimoRegistro());

                for (int i = 0; i < plazo; i++) {
                    intereses = monto * in;

                    Calendar calendar = Calendar.getInstance();
                    calendar.setTime(fechaActual); // Configuramos la fecha que se recibe
                    calendar.add(Calendar.MONTH, 1);
                    fechaActual = calendar.getTime();

                    amortizacion = new Amortizacion(fechaActual, monto, cuota - intereses, intereses, cuota, monto, x.getId());
                    monto = monto - (cuota - intereses);
                    amortizacion.setSaldoFinal(monto);

                    controladorAmortizacion.Agregar(amortizacion);
                    listaAmortizacion.add(amortizacion);
                }
                JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "DEBE DE INGRESAR UN MONTO VALIDO Y PLAZO VALIDO CORRESPONDIENTE","ERROR", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "COMPLETE CAMPOS", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrar1ActionPerformed
        // TODO add your handling code here:
        if (comboTipo.getSelectedIndex() != 0 && !CajaMonto.getText().equals("")) {
            credito = listaCreditos.get(comboTipo.getSelectedIndex() - 1);
            cuota = obtenerCuota();
            CajaCuota.setText("" + formaPrecio.format(cuota));
        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE UN TIPO DE CREDITO Y INGRESE MONTO", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrar1ActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
        CajaCuota.setText("");
    }//GEN-LAST:event_comboTipoActionPerformed

    private void comboFiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiadorActionPerformed
        // TODO add your handling code here:
        if (comboFiador.getSelectedIndex() == 0) {
            txtNombreFiador.setVisible(false);
            txtDuiFiador.setVisible(false);
            txtNitFiador.setVisible(false);
            txtFuente.setVisible(false);
            TxtDatos.setVisible(false);

            CajaNombreFiador.setVisible(false);
            CajaDuiFiador.setVisible(false);
            CajaNitFiador.setVisible(false);
            CajaFuente.setVisible(false);

            CajaNombreFiador.setText("");
            CajaDuiFiador.setText("");
            CajaNitFiador.setText("");
            CajaFuente.setText("");

        } else {
            txtNombreFiador.setVisible(true);
            txtDuiFiador.setVisible(true);
            txtNitFiador.setVisible(true);
            txtFuente.setVisible(true);
            TxtDatos.setVisible(true);

            CajaNombreFiador.setVisible(true);
            CajaDuiFiador.setVisible(true);
            CajaNitFiador.setVisible(true);
            CajaFuente.setVisible(true);

            CajaNombreFiador.setText("");
            CajaDuiFiador.setText("");
            CajaNitFiador.setText("");
            CajaFuente.setText("");
        }
    }//GEN-LAST:event_comboFiadorActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistrarClientes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaCuota;
    private javax.swing.JTextField CajaDui;
    private javax.swing.JTextField CajaDuiFiador;
    private javax.swing.JTextField CajaFecha;
    private javax.swing.JTextField CajaFuente;
    private javax.swing.JTextField CajaMonto;
    private javax.swing.JTextField CajaNitFiador;
    private javax.swing.JTextField CajaNombre;
    private javax.swing.JTextField CajaNombreFiador;
    private javax.swing.JTextField CajaPlazo;
    private javax.swing.JLabel Txt4;
    private javax.swing.JLabel TxtApellidos;
    private javax.swing.JLabel TxtDatos;
    private javax.swing.JLabel TxtDui;
    private javax.swing.JLabel TxtDui1;
    private javax.swing.JLabel TxtDui2;
    private javax.swing.JLabel TxtDui3;
    private javax.swing.JLabel TxtNombre2;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonRegistrar1;
    private javax.swing.JComboBox<String> comboFiador;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtDuiFiador;
    private javax.swing.JLabel txtFuente;
    private javax.swing.JLabel txtNitFiador;
    private javax.swing.JLabel txtNombreFiador;
    // End of variables declaration//GEN-END:variables

    private void llenarCombo() {
        comboTipo.addItem("SELECCIONE");
        for (int i = 0; i < listaCreditos.size(); i++) {
            comboTipo.addItem(listaCreditos.get(i).getTipo());
        }
    }

    private boolean validar() {
        //
        if (comboTipo.getSelectedIndex() == 0 || CajaMonto.getText().equals("")) {
            return false;
        } else if (CajaPlazo.getText().equals("") || CajaCuota.getText().equals("")) {
            return false;
        } else if (comboFiador.getSelectedIndex() == 1) {
            if (CajaNombreFiador.getText().equals("") || CajaNitFiador.getText().equals("") || CajaDuiFiador.getText().equals("") || CajaFuente.getText().equals("")) {
                return false;
            }
        }
        return true;
    }

    private Double obtenerCuota() {
        Double pagoMensual = 0.00;
        Double p = Double.parseDouble(CajaMonto.getText());

        Double i = credito.getInteres() / 12;
        int n = Integer.parseInt(CajaPlazo.getText());
        i = i / 100;

        pagoMensual = (p * i) / (1 - Math.pow(1 / (1 + i), n));

        return pagoMensual;
    }

    private void validarCombo() {
        comboTipo.setEnabled(false);
        for (int i = 0; i < listaCreditos.size(); i++) {
            if (listaCreditos.get(i).getId() == prestamo.getIdCredito()) {
                comboTipo.setSelectedIndex(i + 1);
            }
        }
    }

}
