/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class RegistrarActivoFijo extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarActivoFijo() {
        initComponents();
        setSize(900, 660);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNit = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        CajaNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Direccion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        TxtNit1 = new javax.swing.JLabel();
        CajaNit1 = new javax.swing.JTextField();
        TxtNit2 = new javax.swing.JLabel();
        CajaNit2 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TxtNit4 = new javax.swing.JLabel();
        TxtNit3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 80, 930, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUEVO ACTIVO FIJO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 310, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CATEGORIA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 130, 30);

        TxtNit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit.setText("CODIGO");
        getContentPane().add(TxtNit);
        TxtNit.setBounds(20, 240, 130, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "CAT 1", "CAT 2", "CAT 3" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(140, 100, 200, 30);
        getContentPane().add(CajaNit);
        CajaNit.setBounds(140, 240, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DESCRIPCION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 180, 100, 30);

        Direccion.setColumns(20);
        Direccion.setRows(5);
        jScrollPane1.setViewportView(Direccion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 170, 200, 100);

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 520, 100, 30);

        botonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar);
        botonRegistrar.setBounds(530, 520, 110, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "CAT 1", "CAT 2", "CAT 3" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(560, 100, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SUBCATEGORIA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 100, 130, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DEPTO 1", "DEPTO2", "DEPTO 3" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(140, 170, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEPARTAMENTO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MARCA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 310, 130, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "MARCA 1", "MARCA 2", "MARCA 3", "..." }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(140, 310, 200, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PROVEEDOR");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 310, 130, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "PROV 1", "PROV 2", "PROV 3", "...." }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(560, 310, 200, 30);

        TxtNit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit1.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit1.setText("SERIE/MARCA");
        getContentPane().add(TxtNit1);
        TxtNit1.setBounds(20, 380, 130, 30);
        getContentPane().add(CajaNit1);
        CajaNit1.setBounds(140, 380, 200, 30);

        TxtNit2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit2.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit2.setText("PRECIO");
        getContentPane().add(TxtNit2);
        TxtNit2.setBounds(440, 380, 130, 30);
        getContentPane().add(CajaNit2);
        CajaNit2.setBounds(560, 380, 200, 30);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "NUEVO", "USADO" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(560, 460, 200, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CONDICION");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 460, 130, 30);

        TxtNit4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit4.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit4.setText("INICIO DE USO");
        getContentPane().add(TxtNit4);
        TxtNit4.setBounds(20, 460, 130, 30);

        TxtNit3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtNit3.setForeground(new java.awt.Color(255, 255, 255));
        TxtNit3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TxtNit3.setText("DOCANCION");
        getContentPane().add(TxtNit3);
        TxtNit3.setBounds(20, 530, 130, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(140, 460, 200, 30);

        jCheckBox1.setText("DONADO");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(140, 530, 69, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bitcoin_1600x900_10536.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -70, 920, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistrarClientes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaNit;
    private javax.swing.JTextField CajaNit1;
    private javax.swing.JTextField CajaNit2;
    private javax.swing.JTextArea Direccion;
    private javax.swing.JLabel TxtNit;
    private javax.swing.JLabel TxtNit1;
    private javax.swing.JLabel TxtNit2;
    private javax.swing.JLabel TxtNit3;
    private javax.swing.JLabel TxtNit4;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
