/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCategoria;
import Controlador.ControladorUsuario;
import Modelo.Categoria;
import Modelo.Encriptacion;
import Modelo.Usuario;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jose
 */
public class UsuariosRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuariosRegistro
     */
    JDesktopPane es;
    DefaultTableModel modelo;
    ControladorUsuario ctrUsuario;
    ArrayList<Usuario> usuarios;
    int posicion = -1;
    Usuario objeto;

    public UsuariosRegistro(JDesktopPane escritorio) {
        initComponents();
        es = escritorio;
        ctrUsuario = new ControladorUsuario();
        modelo();
        acctualizarTabla();
        tblDatos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                leerDatos(e);
            }

        });
        lblNueva.setVisible(false);
        txtNuvaContraseña.setVisible(false);
        checkCambio.setVisible(false);
    }

    private void modelo() {

        modelo = new DefaultTableModel();
        modelo.addColumn("#");
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Nivel");

        tblDatos.setModel(modelo);
        TableColumnModel columnModel = tblDatos.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(250);
    }

    public void leerDatos(MouseEvent e) {
        int row = tblDatos.rowAtPoint(e.getPoint());
        posicion = Integer.parseInt(tblDatos.getValueAt(row, 0).toString());
        objeto = new Usuario();
        objeto = usuarios.get(posicion - 1);
        limpiar();
        txtUsuario.setEditable(false);
        lblNueva.setVisible(true);
        checkCambio.setVisible(true);
        checkCambio.setSelected(false);
        jbtmodificar.setEnabled(true);
        txtNuvaContraseña.setVisible(true);
        txtUsuario.setText(objeto.getUser());
        btnAgregar.setEnabled(false);
        comboNivel.setSelectedIndex(objeto.getNivel() + 1);

        jButton3.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jbtmodificar = new javax.swing.JButton();
        lblNueva = new javax.swing.JLabel();
        txtNuvaContraseña = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        comboNivel = new javax.swing.JComboBox<>();
        checkCambio = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        jLabel2.setText("Nombre de usuario:");

        jLabel3.setText("Contraseña:");

        jLabel5.setText("Tipo de usuario:");

        btnAgregar.setText("Crear");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jbtmodificar.setText("Modificar");
        jbtmodificar.setEnabled(false);
        jbtmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtmodificarActionPerformed(evt);
            }
        });

        lblNueva.setText("Nueva contraseña:");

        jButton3.setText("Eliminar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione...", "Administrador", "Gerente de activo fijo", "Gerente de cuentas por cobrar" }));

        checkCambio.setText("Cambiar contraseña");
        checkCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtContraseña))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNueva)
                                    .addComponent(txtNuvaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboNivel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtmodificar)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(checkCambio)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNueva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuvaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkCambio)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jbtmodificar)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        if (validarCampo()) {
            if (ctrUsuario.buscarUsuario(txtUsuario.getText()) == null) {
                String usuario = txtUsuario.getText();
                String contraseña = Encriptacion.getStringMessageDigest(txtContraseña.getText(), Encriptacion.SHA256);
                int tipoUsu = comboNivel.getSelectedIndex() - 1;
                Usuario obj = new Usuario(usuario, contraseña, tipoUsu);
                ctrUsuario.AgregarUsuario(obj);

                acctualizarTabla();

                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Nombre de usuario ya registrado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campos necesarios");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jbtmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtmodificarActionPerformed
        // TODO add your handling code here:

        if (checkCambio.isSelected()) {
            if (validarCampo()) {
                if (objeto.getPass().equals(Encriptacion.getStringMessageDigest(txtContraseña.getText(), Encriptacion.SHA256))) {
                    objeto.setPass(Encriptacion.getStringMessageDigest(txtNuvaContraseña.getText(), Encriptacion.SHA256));
                    objeto.setNivel(comboNivel.getSelectedIndex() - 1);

                    lblNueva.setVisible(false);
                    txtNuvaContraseña.setVisible(false);
                    jbtmodificar.setEnabled(false);
                    jButton3.setEnabled(false);
                    btnAgregar.setEnabled(true);
                    txtUsuario.setEditable(true);
                    ctrUsuario.ModificarUsuario(objeto);
                    limpiar();
                    acctualizarTabla();
                    JOptionPane.showMessageDialog(null, "Datos Modificados");
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta, ingrese la contraseña antigua\n para poder cambiar contraseña");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Campos necesarios");
            }
        } else {

            objeto.setNivel(comboNivel.getSelectedIndex() - 1);

            lblNueva.setVisible(false);
            txtNuvaContraseña.setVisible(false);
            jbtmodificar.setEnabled(false);
            jButton3.setEnabled(false);
            btnAgregar.setEnabled(true);
            txtUsuario.setEditable(true);
            ctrUsuario.ModificarUsuario(objeto);
            limpiar();
            acctualizarTabla();
            JOptionPane.showMessageDialog(null, "Datos Modificados");
        }


    }//GEN-LAST:event_jbtmodificarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        ctrUsuario.EliminarUsuario(objeto);
        lblNueva.setVisible(false);
        txtNuvaContraseña.setVisible(false);
        btnAgregar.setEnabled(true);
        jbtmodificar.setEnabled(false);
        jButton3.setEnabled(false);
        txtUsuario.setEditable(true);
        limpiar();
        acctualizarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void checkCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCambioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JCheckBox checkCambio;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtmodificar;
    private javax.swing.JLabel lblNueva;
    private javax.swing.JTable tblDatos;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JPasswordField txtNuvaContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    public boolean validarCampo() {
        boolean validado = true;
        if (txtContraseña.getText().equals("")) {
            validado = false;
        }
        if (comboNivel.getSelectedIndex() == 0) {
            validado = false;
        }
        return validado;
    }

    public void limpiar() {

        txtContraseña.setText("");
        comboNivel.setSelectedIndex(0);
        txtUsuario.setText("");
        txtNuvaContraseña.setText("");
        checkCambio.setVisible(false);
    }

    public void acctualizarTabla() {
        usuarios = new ArrayList<>();
        usuarios = ctrUsuario.listaUsuarios();

        modelo.setRowCount(usuarios.size());
        for (int i = 0; i < usuarios.size(); i++) {
            modelo.setValueAt(i + 1, i, 0);
            modelo.setValueAt(usuarios.get(i).getUser(), i, 1);
            modelo.setValueAt(usuarios.get(i).getPass(), i, 2);
            if (usuarios.get(i).getNivel() == 0) {
                modelo.setValueAt("Administrador", i, 3);
            } else if (usuarios.get(i).getNivel() == 1) {
                modelo.setValueAt("Gerente de activo fijo", i, 3);
            } else {
                modelo.setValueAt("Gerente de cuentas por cobrar", i, 3);
            }
        }
        tblDatos.setModel(modelo);
    }
}
